export const INIT_REVIEWS = 'INIT_REVIEWS';
export const ADD_REVIEW = 'ADD_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const CHANGE_STATUS_REVIEW = 'DELETE_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
